### ISSUE TITLE
Vimspectorpy#update failed to find vimspector configurations directory

### ISSUE THREAD

**Issue by drusmanbashir** [sagi-z/vimspectorpy#11]
Hi I am using vimspectorpy on neovim latest version. My plugins file has the following vimspector paths set up:

```
  use {"puremourning/vimspector",
    config = function()
      vim.g.vimspector_enable_mappings = "HUMAN"
      vim.g.vimspector_base_dir = "/home/ub/.config/vimspector-config"
      vim.g["vimspector_sign_priority"]= {
        vimspectorBP=39,
        vimspectorBPCon=38,
        vimspectorBPLog=37,
        vimspectorBPDisabled=36,
        vimspectorPC=999,

      }
    end,
   }
  use "sagi-z/vimspectorpy"
```

Yet when I run Vimspectorpy update right after installing, i get the error above. I really want to use IPython console in my debug sessions and I think your plugin will be fantastic if i can get it to work. Many thanks

**Comment by sagi-z** [comment]
Should add support for `g:vimspector_base_dir`

**Comment by sagi-z** [comment]
Hi @drusmanbashir, thanks for reporting this issue.
Please try using the fixed branch and if it works I'll merge it to the master:
```
Plug 'sagi-z/vimspectorpy', { 'branch': 'vimspector_base_dir', 'do': { -> vimspectorpy#update() } }
```

**Comment by drusmanbashir** [comment]
Thanks. Could you please post the 'packer' version of this installation? I am not very literate in vim and lua. Apologies

**Comment by drusmanbashir** [comment]
Ok the error message has disappeared. Now when i select 'debug this file' , vanilla vimspector launches as usual (no Ipython). I have tried the :Pyconsole command with various options for [name] (including 'Pyconsole' ), but i get the message:
vimspectorpy: No registered implementation for window launcher ''  

I have tmux installed in the system, but i use native vim repl btw (iron-vim). Perhaps thats the reason? Not sure.. below is my vimspector config file, I hope it helps:


'`{
  "$schema": "https://puremourning.github.io/vimspector/schema/vimspector.schema.json",
  "adapters": {
    "run_with_debugpy": {
      "command": ["/home/ub/.config/vimspector-config/configurations/linux/_all/run_with_me"],
      "port": 9876,
      "env": {
        "DEBUG_PORT": "9876"
      }
    },
    "python-remote-docker": {
      "variables": {
        "port": "8765"
      },
      "port": "${port}",
      "launch": {
        "remote": {
          "container": "${ContainerID}",
          "runCommand": [
            "python",
            "-m",
            "debugpy",
            "--listen",
            "0.0.0.0:${port}",
            "--wait-for-client",
            "%CMD%"
          ]
        },
        "delay": "5000m"
      }
    },
    "python-remote-ssh": {
      "extends": "python-remote-docker",
      "host": "${host}",
      "launch": {
        "remote": {
          "!container": "REMOVE",
          "!delay": "REMOVE",

          "!!test": "This is a !test",

          "host": "${host}",
          "account": "${account}"
        }
      }
    }
  },
  "configurations": {
    "run-stepinto-3rd-party-code": {
      "adapter": "debugpy",
      "configuration": {
        "request": "launch",
        "justMyCode": false,
        "type": "python",
        "cwd": "${workspaceRoot}",
        "program": "${file}",
        "stopOnEntry": false,
        "console": "integratedTerminal",
        "env": {
                "PYTHONPATH":"/home/ub/Dropbox/code/kits19/"
            }
      },
      "breakpoints": {
        "exception": {
          "raised": "N",
          "uncaught": "",
          "userUnhandled": ""
        }
      }
    }

  }
}`

**Comment by drusmanbashir** [comment]
Ok the error message has disappeared. Now when i select 'debug this file' , vanilla vimspector launches as usual (no Ipython). I have tried the :Pyconsole command with various options for [name] (including 'Pyconsole' ), but i get the message:
vimspectorpy: No registered implementation for window launcher ''  

I have tmux installed in the system, but i use native vim repl btw (iron-vim). Perhaps thats the reason? Not sure.. below is my vimspector config file, I hope it helps:


```
{
  "$schema": "https://puremourning.github.io/vimspector/schema/vimspector.schema.json",
  "adapters": {
    "run_with_debugpy": {
      "command": ["/home/ub/.config/vimspector-config/configurations/linux/_all/run_with_me"],
      "port": 9876,
      "env": {
        "DEBUG_PORT": "9876"
      }
    },
    "python-remote-docker": {
      "variables": {
        "port": "8765"
      },
      "port": "${port}",
      "launch": {
        "remote": {
          "container": "${ContainerID}",
          "runCommand": [
            "python",
            "-m",
            "debugpy",
            "--listen",
            "0.0.0.0:${port}",
            "--wait-for-client",
            "%CMD%"
          ]
        },
        "delay": "5000m"
      }
    },
    "python-remote-ssh": {
      "extends": "python-remote-docker",
      "host": "${host}",
      "launch": {
        "remote": {
          "!container": "REMOVE",
          "!delay": "REMOVE",

          "!!test": "This is a !test",

          "host": "${host}",
          "account": "${account}"
        }
      }
    }
  },
  "configurations": {
    "run-stepinto-3rd-party-code": {
      "adapter": "debugpy",
      "configuration": {
        "request": "launch",
        "justMyCode": false,
        "type": "python",
        "cwd": "${workspaceRoot}",
        "program": "${file}",
        "stopOnEntry": false,
        "console": "integratedTerminal",
        "env": {
                "PYTHONPATH":"/home/ub/Dropbox/code/kits19/"
            }
      },
      "breakpoints": {
        "exception": {
          "raised": "N",
          "uncaught": "",
          "userUnhandled": ""
        }
      }
    }

  }
}

```
