### ISSUE TITLE
Uninstallation does not reverse all the effects

### ISSUE THREAD

**Issue by Weyaaron** [sagi-z/vimspectorpy#12]
Dear community,
I installed vimspectorpy, but was confused. After some consideration I decided to stick to my original setup for the moment. Therefore, I uninstalled vimspectorpy. However, there is a  part of the config that has not been reversed: 
```
Vimspector new configurations

Next time you are on a python source and start a debug session (F5) you'll get this option:

    debug this file - launch a debug session for the current file, using the python from your $VIRTUAL_ENV if there is one, or python3.
```
![image](https://user-images.githubusercontent.com/52529582/167417157-4a3b9fb2-a94d-44d9-915f-06bbe537d8f2.png)
This my current  vimspector.json:
```
{
  "$schema": "https://puremourning.github.io/vimspector/schema/vimspector.schema.json",
  "adapters": {
  },
  "configurations": {
    "run - scratch.py": {
      "adapter": "debugpy",
      "configuration": {
        "request": "launch",
        "default": true,
        "type": "python",
        "cwd": "${workspaceRoot}",
        "program": "${workspaceRoot}/scratch.py",
        "args" : ["crawl"],
        "stopOnEntry": false,
        "console": "integratedTerminal",
        "python": ["/home/aaron/.conda/envs/qse/bin/python"]
      },
      "breakpoints":{
        "exception": {
          "raised": "Y",
          "uncaught": "Y",
          "userUnhandled": "Y"
        }
      }
    }
  }
}
```
I would like to revert this config, but I lack the knowledge how to do this. Any input is appreciated. 

Greetings,
Aaron

**Comment by sagi-z** [comment]
Hi @Weyaaron , to remove `vimspectorpy` completely please do this (assuming a normal plugin install on linux):
```
find ~/.vim/plugged/vimspector/configurations -name '*vimspectorpy.json' -delete
```
I'll update the documentation for this.

**Comment by Weyaaron** [comment]
This file has been deleted, I appreciate the feedback :)
