### ISSUE TITLE
No registered implementation for window launcher ''

### ISSUE THREAD

**Issue by ferdinandyb** [sagi-z/vimspectorpy#13]
I'm getting this error when trying to run `:Pyconsole`:
```
vimspectorpy: No registered implementation for window launcher ''
```

how can I fix this?

**Comment by sagi-z** [comment]
https://github.com/sagi-z/vimspectorpy#gvimspectorpylauncher

**Comment by ferdinandyb** [comment]
Ah, my bad, sorry for not reading the manual properly! Have you considered maybe adding a kitty split to the possibilities?

**Comment by ferdinandyb** [comment]
Anyhow, it works great in tmux, so I'm closing this issue, sorry for the noise.
